### ISSUE TITLE
node.set not needed in default recipe

### ISSUE THREAD

**Issue by brugidou** [schubergphilis/nrpe#27]
There is no need to set the nrpe.checks attribute with the set/normal priority. Default priority should be enough and would not mess with the node's persistent data.

See https://github.com/tas50/chef-nrpe/blob/af28f203aaf35ac6e94931a14de6b89c534ded81/recipes/default.rb#L83

Just to get a bit of context: we are managing nodes with git in our organization in a static way (since they are bare metal) and we have a script that check for synchronization b/t git and the chef server. Normal attributes are persistent data that we store in git as opposed to default/overrides which are generated during each chef run by roles/environments/cookbooks. Having normal attributes on a node mean that the cookbook requested to "store" some attribute across chef runs.

**Comment by glensc** [comment]
so, you propose to use `default`?

```ruby
    node.default['nrpe']['checks'] = checks
```

**Comment by brugidou** [comment]
Yes

**Comment by sspans** [comment]
That would also resolve the following warning from newer chef clients.

```
  node.set is deprecated and will be removed in Chef 14, please use node.default/node.override (or node.normal only if you really need persistence) at 2 locations:
    - /var/chef/cache/cookbooks/nrpe/recipes/default.rb:83:in `block (2 levels) in from_file'
```
