### ISSUE TITLE
build-essential dependency

### ISSUE THREAD

**Issue by CpuID** [schubergphilis/nrpe#32]
Hey there,

I am interested in using this cookbook, but the dependency on build-essential is steering me away... :) Is the only thing mandating that right now the source installation option? Do you know if it is widely used? build-essential definitely makes this quite a heavy install, especially if using a packaged install.

Thanks.

**Comment by tas50** [comment]
Nathan,

Build-essential is a required part of installation for anyone doing source
installs and it needs to be in the metadata for those users.  if you're
doing a package based install that code will never execute and there's no
harm in including it in the metadata.

-Tim
