### ISSUE TITLE
systemd deployment is broken

### ISSUE THREAD

**Issue by anuriq** [schubergphilis/nrpe#50]
Good day.

After 1.5.3 release, I could not help but notice that converging on systemd OSes (> Centos 7) fails.
I suspect that this PR https://github.com/schubergphilis/nrpe/pull/31 should have changed something very important.

A piece from systemd log:
```
Jul 20 10:41:21 master0-el7 nrpe[14498]: Unable to open config file '/etc/nagios/nrpe.cfg' for reading
Jul 20 10:41:21 master0-el7 nrpe[14498]: Config file '/etc/nagios/nrpe.cfg' contained errors, aborting...
Jul 20 10:41:21 master0-el7 systemd[1]: nrpe.service: control process exited, code=exited status=2```

**Comment by snkutlu** [comment]
New release 1.5.4 is on its way and I hope it will fix also that issue.. Waiting for a 

@anuriq Can you please re-try when 1.5.4 is available?

**Comment by snkutlu** [comment]
@anuriq v1.5.5 is released (due to my mistake, it is not 1.5.4 unfortunately). Can you please try when you have time?

**Comment by anuriq** [comment]
will check now

**Comment by anuriq** [comment]
looks OK. will confirm for sure after heavy converges. but let's close this for now.
